const actionTypes = {
  GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',

  CREATE_USERS_REQUESTED: 'CREATE_USERS_REQUESTED',
  CREATE_USERS_SUCCESS: 'CREATE_USERS_SUCCESS',
  CREATE_USERS_FAILED: 'CREATE_USERS_FAILED',
  
  DELETE_USERS_REQUESTED: 'DELETE_USERS_REQUESTED',
  DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
  DELETE_USERS_FAILED: 'DELETE_USERS_FAILED', 
  
  UPDATE_USERS_REQUESTED: 'UPDATE_USERS_REQUESTED',
  UPDATE_USERS_SUCCESS: 'UPDATE_USERS_SUCCESS',
  UPDATE_USERS_FAILED: 'UPDATE_USERS_FAILED',

  GET_USERS_BYID_REQUESTED: 'GET_USERS_BYID_REQUESTED',
  GET_USERS_BYID_SUCCESS: 'GET_USERS_BYID_SUCCESS',
  GET_USERS_BYID_FAILED: 'GET_USERS_BYID_FAILED',
};

export default actionTypes;